export const GET_CURRENT_USER_GUILDS_REQUEST = 'GET_CURRENT_USER_GUILDS_REQUEST';
export const GET_CURRENT_USER_GUILDS_SACCESS = 'GET_CURRENT_USER_GUILDS_SACCESS';
export const GET_CURRENT_USER_GUILDS_ERROR = 'GET_CURRENT_USER_GUILDS_ERROR';

export const GET_CHANNELS_REQUEST = 'GET_CHANNELS_REQUEST';
export const GET_CHANNELS_SACCESS = 'GET_CHANNELS_SACCESS';
export const GET_CHANNELS_ERROR = 'GET_CHANNELS_ERROR';