export const GET_CURRENT_USER_GUILDS_REQUEST = 'GET_CURRENT_USER_GUILDS_REQUEST';
export const GET_CURRENT_USER_GUILDS_SACCESS = 'GET_CURRENT_USER_GUILDS_SACCESS';
export const GET_CURRENT_USER_GUILDS_ERROR = 'GET_CURRENT_USER_GUILDS_ERROR';

export const GET_CHANNELS_REQUEST = 'GET_CHANNELS_REQUEST';
export const GET_CHANNELS_SACCESS = 'GET_CHANNELS_SACCESS';
export const GET_CHANNELS_ERROR = 'GET_CHANNELS_ERROR';

export const SEARCH_GUILD_TEXT_REQUEST = 'SEARCH_GUILD_TEXT_REQUEST';
export const SEARCH_GUILD_TEXT_SACCESS = 'SEARCH_GUILD_TEXT_SACCESS';
export const SEARCH_GUILD_TEXT_ERROR = 'SEARCH_GUILD_TEXT_ERROR';

export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SACCESS = 'GET_USER_SACCESS';
export const GET_USER_ERROR = 'GET_USER_ERROR';

export const GET_ME_REQUEST = 'GET_ME_REQUEST';
export const GET_ME_SACCESS = 'GET_ME_SACCESS';
export const GET_ME_ERROR = 'GET_ME_ERROR';