export const ADD_NOTIFICATION_REQUEST = 'ADD_NOTIFICATION_REQUEST';
export const ADD_NOTIFICATION_SACCESS = 'ADD_NOTIFICATION_SUCCESS';
export const ADD_NOTIFICATION_ERROR = 'ADD_NOTIFICATION_ERROR';

export const REMOVE_NOTIFICATION_REQUEST = 'REMOVE_NOTIFICATION_REQUEST';
export const REMOVE_NOTIFICATION_SUCCESS = 'REMOVE_NOTIFICATION_SUCCESS';
export const REMOVE_NOTIFICATION_ERROR = 'REMOVE_NOTIFICATION_ERROR';