export const SET_COMMENTS_GROUP_REQUEST = 'SET_COMMENTS_GROUP_REQUEST';
export const SET_COMMENTS_GROUP_SACCESS = 'SET_COMMENTS_GROUP_SACCESS';
export const SET_COMMENTS_GROUP_ERROR = 'SET_COMMENTS_GROUP_ERROR';