export const SET_API_KEY_REQUEST = 'SET_API_KEY_REQUEST';
export const SET_API_KEY_SACCESS = 'SET_API_KEY_SUCCESS';
export const SET_API_KEY_ERROR = 'SET_API_KEY_ERROR';

export const DELETE_API_KEY_REQUEST = 'DELETE_API_KEY_REQUEST';
export const DELETE_API_KEY_SACCESS = 'DELETE_API_KEY_SUCCESS';
export const DELETE_API_KEY_ERROR = 'DELETE_API_KEY_ERROR';